-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."softcartDimDate"
(
    dateid integer NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    monthname character(12)[] NOT NULL,
    day integer NOT NULL,
    weekday integer,
    week integer,
    quarter integer,
    PRIMARY KEY (dateid)
);

CREATE TABLE public."softcartDimCategory"
(
    cathegoryid integer NOT NULL,
    cathegory_name character(10)[],
    PRIMARY KEY (cathegoryid)
);

CREATE TABLE public."softcartDimItem"
(
    itemid integer NOT NULL,
    item_designation character(200)[],
    "priAchat" real,
    "priVente" real,
    PRIMARY KEY (itemid)
);

CREATE TABLE public."softcartDimCountry"
(
    countryid integer NOT NULL,
    continent character(32)[],
    country_name character(32)[],
    region character(32)[],
    state character(32)[],
    cartier character(55)[],
    PRIMARY KEY (countryid)
);

CREATE TABLE public."softcartFactSales"
(
    orderid integer NOT NULL,
    quantity integer NOT NULL,
    dateid integer,
    cathegoryid integer,
    itemid integer,
    countryid integer,
    PRIMARY KEY (orderid)
);

ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (cathegoryid)
    REFERENCES public."softcartDimCategory" (cathegoryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid)
    NOT VALID;

END;